#!/bin/sh
#
# /usr/sbin/rotatelog: rotate logfile
#

LOGDIR='/var/log'
OLDDIR="${LOGDIR}/old"

[ $# -ne 1 ] && echo "usage: $0 <logfile>" && exit 1
[ ! -e "${LOGDIR}/$1" ] && exit 1

if [ $(stat -c %s "${LOGDIR}/$1") -gt 100000 ]; then
	[ -e "${OLDDIR}/$1.4.xz" ] && rm ${OLDDIR}/$1.4.xz
	[ -e "${OLDDIR}/$1.3.xz" ] && mv ${OLDDIR}/$1.3.xz ${OLDDIR}/$1.4.xz
	[ -e "${OLDDIR}/$1.2.xz" ] && mv ${OLDDIR}/$1.2.xz ${OLDDIR}/$1.3.xz
	[ -e "${OLDDIR}/$1.1.xz" ] && mv ${OLDDIR}/$1.1.xz ${OLDDIR}/$1.2.xz
	xz -9c ${LOGDIR}/$1 > ${OLDDIR}/$1.1.xz && > ${LOGDIR}/$1
fi

# End of file
